### ISSUE TITLE
Unable to update to CircularProgressBar 1.3.0

### ISSUE THREAD

**Issue by tumbling-dice** [castorflex/SmoothProgressBar#100]
>Error:Could not find library-circular.jar (com.github.castorflex.smoothprogressbar:library-circular:1.3.0).
>Searched in the following locations:
>    https://repo1.maven.org/maven2/com/github/castorflex/smoothprogressbar/library-circular/1.3.0/library-circular-1.3.0.jar

It is probably because there is no `.aar` file.

**Comment by castorflex** [comment]
Thanks, I'll look into this

**Comment by jakubbegera** [comment]
Hi,
please could you add missing aar file into maven repo for com.github.castorflex.smoothprogressbar:library-circular:1.3.0? 
Thanks

**Comment by castorflex** [comment]
Should be ok now
