### ISSUE TITLE
how to set the color of the Circularprogressbar

### ISSUE THREAD

**Issue by kllkko** [castorflex/SmoothProgressBar#101]
Hi , There doesn't seem to be a way to properly set the colour of the CircularProgressDrawable.
I have set the defaullt colour is blue in my xml：

                   <fr.castorflex.android.circularprogressbar.CircularProgressBar
                            android:id="@+id/loading_status"
                            android:layout_width="117dp"
                            android:layout_height="117dp"
                            android:indeterminate="true"
                            app:cpb_color="@color/blue"
                            android:layout_centerInParent="true"/>

then I want to change the color by doing this:
      loadingView.setIndeterminateDrawable(new   CircularProgressDrawable.Builder(mContext).color(getResources().getColor(R.color.green)).build());

but it seems not work,please help me ,thank you

**Comment by kllkko** [comment]
sorry it is my fault , already fixed now

**Comment by ryanamaral** [comment]
You can change the color of the running progress animation by calling `setColorFilter`.
I set the color white in the xml layout:
```
<fr.castorflex.android.circularprogressbar.CircularProgressBar
                        app:cpb_color="#ffffff" // white
...
```
And applied to the desired color (yellow in the example) programmatically:
`circularProgressBar.indeterminateDrawable.setColorFilter(Color.YELLOW, PorterDuff.Mode.MULTIPLY)`
