### ISSUE TITLE
SmoothProgressBar starts on resume activity

### ISSUE THREAD

**Issue by Thermometer91** [castorflex/SmoothProgressBar#35]
Heya, 

My compliments for this awesome library! I love the way I can customize the progress bar on so many levels. 

I am running into an issue with my progress bar starting, when my activity resumes (after  dismissing another activity and coming back to the progress bar activity). 

I tried to handle it with the `setSmoothProgressDrawableCallbacks`, and handling hiding & showing in the `onStop()` and `onStart()` methods, but this doesn't give the expected result. 

I am initializing my progress bar in my activity's `onCreate()`: 

``` Java
mProgressBar = (SmoothProgressBar) findViewById(R.id.route_detail_progressbar);
mProgressBar.setVisibility(View.VISIBLE);
mProgressBar.setSmoothProgressDrawableCallbacks(new ProgressBarListener());
mProgressBar.progressiveStart();
```

And having customized the progress bar in XML: 

``` XML
<fr.castorflex.android.smoothprogressbar.SmoothProgressBar
        xmlns:android="http://schemas.android.com/apk/res/android"
        android:id="@+id/route_detail_progressbar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:indeterminate="true"
        android:layout_marginTop="-3dp"
        android:visibility="gone"
        app:spb_sections_count="2"
        app:spb_color="@color/Primary"
        app:spb_speed="0.7"
        app:spb_stroke_width="7dp"
        app:spb_stroke_separator_length="16dp"
        app:spb_reversed="false"
        app:spb_mirror_mode="false"
        app:spb_progressiveStart_activated="true"
        app:spb_progressiveStart_speed="1.5"
        app:spb_progressiveStop_speed="3.4"
        />
```

Without adding the `ProgressBarListener`, everything works as expected, except that when the activity comes in view, it starts again. 

My `ProgressBarListener`:

``` Java
private class ProgressBarListener implements SmoothProgressDrawable.Callbacks
    {
        @Override
        public void onStop() {
            mProgressBar.setVisibility(View.GONE);
        }

        @Override
        public void onStart() {
            mProgressBar.setVisibility(View.VISIBLE);
        }
    }
```

With the listener, I don't see the progress bar at all. 

Do you have any idea what I am doing wrong? I've put breakpoints in the listener, and it seems that `onStop()` is called first, then `onStart()` is called twice strangely enough. 

Thanks in advance!

**Comment by drindt** [comment]
Here seems that:
```
android:indeterminate="true"
```

is the problem. When this is set
```
app:spb_progressiveStart_activated="true"
``` 
is totally ignored. Setting this all programmatically seems fine.
