### ISSUE TITLE
Determinate mode

### ISSUE THREAD

**Issue by duduBaiao** [castorflex/SmoothProgressBar#70]
Hi! Is it possible to use SmoothProgressBar when "indeterminate" is set to "false"?

Nothing shows when I use the xml above:

    <fr.castorflex.android.smoothprogressbar.SmoothProgressBar
        android:layout_width="match_parent"
        android:layout_height="2dp"
        android:indeterminate="false"
        android:progress="25"
        android:max="100"
        app:spb_sections_count="4"
        app:spb_color="#FF0000"
        app:spb_speed="1.0"
        app:spb_stroke_width="2dp"
        app:spb_stroke_separator_length="4dp"
        app:spb_reversed="false"
        app:spb_mirror_mode="false"/>

**Comment by castorflex** [comment]
You have to set a style to use the stock progress horizontal drawable (or a progressDrawable + minHeight + maxHeight +indeterminateOnly=false). The easiest way to do this is to use `style=@style/SmoothProgressBar`, or define your own.

**Comment by RankoR** [comment]
Add this to docs on main page plz.
