### ISSUE TITLE
Circular progress bar :  artefacts

### ISSUE THREAD

**Issue by Alkimisticus** [castorflex/SmoothProgressBar#76]
I get white artefact/patches as show in image, after completion of Intent (facebook login). 

![circular_progress_bar_artefacts](https://cloud.githubusercontent.com/assets/309801/7537248/9d25bd3e-f597-11e4-9e55-21ceff40f693.png)

They allways show, only at the points of the compass.  But not all, sometimes one sometimes two or even three and they remain unchanged.

**Comment by castorflex** [comment]
Hi there. These artifacts are probably caused by the bounds of the drawable and a float to int cast. 
Are you using the last version of the library (v1.1.0)? 
If you are, would it be possible for you to send me a small sample project reproducing the issue ?\\

Regards.

**Comment by Alkimisticus** [comment]
Hi I'm using latest library 

Sample layout 

<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:custom="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools" android:layout_width="match_parent"
    android:layout_height="match_parent" android:background="#231f20"
    tools:context=".FullscreenActivity">

    <fr.castorflex.android.circularprogressbar.CircularProgressBar
        android:layout_marginTop="30dp"
        android:layout_width="250dp"
        android:layout_height="250dp"
        android:layout_gravity="center"
        android:indeterminate="true"
        custom:cpb_color="@android:color/white"
        custom:cpb_rotation_speed="1.0"
        custom:cpb_sweep_speed="1.0"
        custom:cpb_stroke_width="4dp"
        custom:cpb_min_sweep_angle="10"
        custom:cpb_max_sweep_angle="300"
        />

</FrameLayout>

Theme is Theme.Black.NoTitleBar.Fullscreen

**When you open app, everything is OK, but than you press square and app again, artefacts appear**

**Comment by castorflex** [comment]
Please reopen the issue if still facing it
