### ISSUE TITLE
CircularProgressBar in Power Saving Mode

### ISSUE THREAD

**Issue by joseffilzmaier** [castorflex/SmoothProgressBar#78]
Hello!

With android 5 came the new Power saving mode. In this mode all animations are ended instantly. The CircularProgressBar is looking pretty weird and hectic if this mode is enabled, as all animations are ended and startet again very quickly. (Can also be reproduced by disabling the animation duration in android developer setting)

Is there any known workaround for this? This has to be possible somehow, because i've seen it working in the gmail app: If you refresh your email list in gmail, a CircularProgressDrawable is shown correctly, also when power saving mode is enabled.

Thanks

**Comment by castorflex** [comment]
Thanks for reporting this, I will have a look asap

**Comment by castorflex** [comment]
Looks like no progressbar at all is shown with te default implementation (see Play Store app). I think this is a quite nice way to go as the user wants to save battery. 
Thoughts?

**Comment by joseffilzmaier** [comment]
I think that just not showing the circular progressbar at all while in power saving mode is fine. Though i have to disagree with the fact that the circular progressbar is not shown per default while in power saving mode. On my android 5.0.1 device while being in power saving mode shows the weird behaviour. (Its the current play store app, i was also able to reproduce this bug by including your library in my application)

Here is a video showing the bug in action using the play store preview app.
https://youtu.be/q5GSO9Xcpqo

**Comment by castorflex** [comment]
I was talking about the real android Play Store application, not the demo of circular progressbar in the Play Store :)

**Comment by joseffilzmaier** [comment]
Ah, i see :)

Yes, you're right, the play store app does not show the progress bar. I think not showing the drawable is the right way to do it.

Still, the gmail app has some trick to show a CircularProgressDrawable in PSM, when refreshing your mails. I'd be curious how this is implemented, maybe it's just a gif or something...

Also, maybe you could add some description in your readme about the CircularProgressDrawable when in power saving mode.

Thanks.

**Comment by castorflex** [comment]
So I've pushed a snapshot version of the fix. You can test it using the following in you gradle file:

```groovy
repositories {
    maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
}

dependencies {
    compile 'com.github.castorflex.smoothprogressbar:library-circular:1.2.0-SNAPSHOT@aar'
}
```

This fix tests if the user is in power save mode each time the drawable is started (a reference to the powermanager is kept permanently).

**Comment by MomenZaq** [comment]
Hi @castorflex 
I face this problem, Is there any solution, please?
Thank you.
