### ISSUE TITLE
CircularProgressDrawable gradient

### ISSUE THREAD

**Issue by gcalaprice** [castorflex/SmoothProgressBar#89]
Hi,
I'm looking for a gradient support for the CircularProgressDrawable. I just want to show a gradient along the arc that is drawn during the progress. Is there a chance to achieve this? Attached below an example of what I want to achieve. Thanks.
![image](https://cloud.githubusercontent.com/assets/3225051/13686148/af4ab89c-e714-11e5-8969-6d00d1c98eeb.png)

**Comment by mochi-logic** [comment]
I have forked and added some gradient code. You should be able to modify my code to get what you want.

**Comment by castorflex** [comment]
I don't plan to add new features at this moment.
