### ISSUE TITLE
Issue on Android Nougat

### ISSUE THREAD

**Issue by hunnydarapstar** [castorflex/SmoothProgressBar#91]
Circular progressbar not animating properly in android nougat. Please check.

**Comment by lukaspili** [comment]
I confirm. It animates fine for ~2 seconds, then starts to degrade.
Do you plan to look into it @castorflex ?
Thanks.

**Comment by hmehta1** [comment]
I am testing on android nougat emulator and the animation stops after 1-2 seconds. Is there any work-around?
Thanks.
