### ISSUE TITLE
How to set background to transparent if used as non-intermediate progress bar

### ISSUE THREAD

**Issue by yccheok** [castorflex/SmoothProgressBar#97]
When using traditional `ProgressBar`, I found out it is difficult to remove its background. This is because they are using drawable, instead of Canvas drawing.

https://stackoverflow.com/questions/24233577/remove-progress-bar-background-in-android-progress-bar

Hence, I decide to use SmoothProgressBar. As, from first look, SmoothProgressBar seem to use intensive Canvas drawing. I thought I could modify its background color to transparent using

        

        <fr.castorflex.android.smoothprogressbar.SmoothProgressBar
            style="@style/SmoothProgressBar"
            android:layout_width="match_parent"
            android:layout_height="8dp"
            android:id="@+id/progress_bar"
            android:layout_gravity="top"
            android:layout_marginBottom="0dp"
            android:layout_marginTop="-4dp"
            android:elevation="4dp"
            android:max="10000"

            android:background="@android:color/transparent"
            app:spb_background="@android:color/transparent"

            android:visibility="gone" />

However, it still have a grey background. Please see my screenshot. The progress in between System status bar and Toolbar.

![screenshot_20170610-042328](https://user-images.githubusercontent.com/308276/26993350-41eec322-4d95-11e7-989a-d517e8e45a3e.png)

Thank you very much. This is a great library. I also used it as intermediate progress bar in other area.

**Comment by castorflex** [comment]
Hello, this library does not handle determinate progress, only indeterminate. This might be implemented one day, but it's not planned at this moment.
